#!/bin/bash

set -ue

ARGOCD_ENV_CDK8S_ENV=${ARGOCD_ENV_CDK8S_ENV:-main}

if [ -f "package.json" ]; then
    # TypeScript support
    npm ci && ts-node "$ARGOCD_ENV_CDK8S_ENV.ts"
    cat dist/*yaml
    exit 0
fi

echo "No matching files found"
exit 1
