#!/bin/bash

set -ue

ARGOCD_ENV_CDK8S_ENV=${ARGOCD_ENV_CDK8S_ENV:-main}

if [ -f "package.json" ]; then
    # TypeScript support: compile to JS and run the JS file
    npm run build && node "$ARGOCD_ENV_CDK8S_ENV.js"
    exit 0
fi

echo "No matching files found"
exit 1
