#!/bin/bash

set -ue

find . -iname 'cdk8s.yaml' | while read -r cdk8s; do
    pushd "$(dirname "$cdk8s")" >/dev/null

    # TypeScript support: cdk8s projects are just npm projects, so we only need to install the depencendencies
    if [ -f "package.json" ]; then
        npm install
    fi

    # TODO: Deno support
    # TODO: Python support
    # TODO: Java support
    # TODO: Go support

    popd >/dev/null
done

